const Types = {
  STATIC_REQUEST: 'STATIC_REQUEST',
  STATIC_SUCCESS: 'STATIC_SUCCESS',
  STATIC_FAILURE: 'STATIC_FAILURE',

  SWITCH_LANGUAGE: 'SWITCH_LANGUAGE',

  POST_LOGIN_REQUEST: 'POST_LOGIN_REQUEST',
  POST_LOGIN_SUCCESS: 'POST_LOGIN_SUCCESS',
  POST_LOGIN_FAILURE: 'POST_LOGIN_FAILURE',
};

export {Types};
